default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username:
  password:
  host: localhost

development:
  <<: *default
  database: allied_health_aged_care_dev

test:
  <<: *default
  database: allied_health_aged_care_test
